gkiga/mem-help

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/static_pages.scss
- app/controllers/static_pages_controller.rb
- app/helpers/static_pages_helper.rb
- app/javascript/packs/application.js
- app/views/static_pages/home.html.erb
- config/routes.rb
- config/webpack/environment.js
- package.json
- test/controllers/static_pages_controller_test.rb
- yarn.lock
Closes #1 
Task Outcome:
Task completed as expected. A user should be able to go to localhost:3000/home and see a welcome/description of the site.
> MH-3 View Home Page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/static_pages.scss
- app/controllers/static_pages_controller.rb
- app/helpers/static_pages_helper.rb
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- app/views/static_pages/home.html.erb
- config/routes.rb
- config/webpack/environment.js
- package.json
- test/controllers/static_pages_controller_test.rb
- yarn.lock
Closes #7 
Task Outcome:
Task completed as expected. A user should be able to go to <https://localhost:3000/home> and see a navbar at the top. The link to "Home" is the only link currently working.
> MH-7 View Navigation Bar

- app/assets/stylesheets/application.scss
- app/controllers/static_pages_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
Closes# 2
Task Description:
Flash notification implemented  
How to Evaluate:
Run the app. Try to sign up for a new profile. Then log on using your profile information.
> MH-2 "Flash notification Fixed"

- app/views/users/show.html.erb
> Added 'Personalize Profile' button and edited 'Direct Request' button

- app/controllers/requests_controller.rb
Closes #20 
Task outcome fixed issue on my request edit page
> fixed issue # 20 

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/messages.scss
- app/controllers/messages_controller.rb
- app/helpers/messages_helper.rb
- app/models/message.rb
- app/models/user.rb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/messages/edit.html.erb
- app/views/messages/index.html.erb
- app/views/messages/new.html.erb
- app/views/messages/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20201017172308_create_messages.rb
- db/schema.rb
- test/controllers/messages_controller_test.rb
- test/fixtures/messages.yml
- test/models/message_test.rb
Closes #27 
Task complete: messages function working where 2 user can communicate through messages.
> MH 8: Implement Messaging: Student and Teacher can send direct messages

- app/controllers/account_videos_controller.rb
- app/controllers/users_controller.rb
- app/views/users/index.html.erb
- app/views/videos/show.html.erb
Closes #32 
Task Outcome:
This task took longer than expected. It was difficult to decide which query would be best for combining users and videos for the search page. However, now it is possible to see a user's videos on the search page.
> MH-26 Search Part 2

- app/controllers/messages_controller.rb
- app/controllers/requests_controller.rb
- app/models/message.rb
- app/models/my_notification.rb
- app/models/request.rb
- db/migrate/20201026154133_add_message_fk_col_to_my_notifications.rb
- db/migrate/20201026154533_add_request_fk_col_to_my_notifications.rb
- db/schema.rb
- test/fixtures/my_notifications.yml
- test/models/my_notification_test.rb
> HOTFIX: Delete Notifications with Message/Request

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/requests/index.html.erb
- app/views/requests/show.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
Closes #43
Task Outcome:
I was able to update the view of multiple pages, such as the requests index page and request show page. I also updated the theme of the site. There may be a Part 2 for making our UX uniform where I will update more pages. Overall, the task was completed as expected.
> MH-28: Uniform UX

- app/assets/stylesheets/follows.scss
- app/controllers/follows_controller.rb
- app/controllers/requests_controller.rb
- app/controllers/reviews_controller.rb
- app/helpers/follows_helper.rb
- app/models/follow.rb
- app/models/my_notification.rb
- app/models/review.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- db/migrate/20201103051316_create_follows.rb
- db/migrate/20201103212528_add_review_fk_col_to_my_notifications.rb
- db/schema.rb
- test/controllers/follows_controller_test.rb
- test/fixtures/follows.yml
- test/fixtures/my_notifications.yml
- test/models/follow_test.rb
- test/models/my_notification_test.rb
> MH-17: Review Notification

- app/assets/stylesheets/account_follows.scss
- app/controllers/account_follows_controller.rb
- app/controllers/users_controller.rb
- app/helpers/account_follows_helper.rb
- app/models/follow.rb
- app/models/my_notification.rb
- app/models/user.rb
- app/views/account_follows/index.html.erb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20201106011002_add_user_fk_col_to_my_notifications.rb
- db/schema.rb
- test/controllers/account_follows_controller_test.rb
- test/fixtures/my_notifications.yml
- test/models/my_notification_test.rb
> MH-19: Follow Tutors

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/actiontext.scss
- app/javascript/packs/application.js
- app/models/message.rb
- app/models/my_notification.rb
- app/views/active_storage/blobs/_blob.html.erb
- app/views/messages/edit.html.erb
- app/views/messages/new.html.erb
- app/views/messages/show.html.erb
- config/initializers/html_sanitization.rb
- db/migrate/20201106041921_create_action_text_tables.action_text.rb
- db/schema.rb
- package.json
- test/fixtures/action_text/rich_texts.yml
- test/fixtures/my_notifications.yml
- test/models/my_notification_test.rb
- yarn.lock
> MH-31 Implement action text

- app/controllers/account_videos_controller.rb
- app/controllers/users_controller.rb
- app/controllers/videos_controller.rb
- app/models/my_notification.rb
- app/models/user.rb
- app/models/video.rb
- app/views/layouts/application.html.erb
- db/migrate/20201106204914_add_video_fk_col_to_my_notifications.rb
- db/schema.rb
- test/fixtures/my_notifications.yml
- test/models/my_notification_test.rb
> MH-20: New Video Notification

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/reviews/index.html.erb
- app/views/reviews/show.html.erb
- db/migrate/20201107194731_add_sender_name_to_reviews.rb
- db/schema.rb
- test/fixtures/reviews.yml
- test/models/review_test.rb
> Mh 14 Enhanced Review (Part 2)

- app/controllers/account_videos_controller.rb
- app/controllers/videos_controller.rb
- app/models/review.rb
- app/models/video.rb
- app/views/account_videos/new.html.erb
- app/views/users/show.html.erb
- app/views/videos/show.html.erb
- db/schema.rb
- test/fixtures/reviews.yml
- test/models/review_test.rb
> MH-30 Video Thumbnails

- app/assets/stylesheets/global_listings.scss
- app/controllers/global_listings_controller.rb
- app/helpers/global_listings_helper.rb
- app/models/global.rb
- app/models/global_listing.rb
- app/models/user.rb
- app/views/global_listings/index.html.erb
- app/views/globals/show.html.erb
- app/views/layouts/application.html.erb
- app/views/requests/index.html.erb
- app/views/requests/show.html.erb
- config/routes.rb
- db/migrate/20201114165227_create_global_listings.rb
- db/migrate/20201114180225_add_global_listing_fk_col_to_globals.rb
- db/schema.rb
- test/controllers/global_listings_controller_test.rb
- test/fixtures/global_listings.yml
- test/fixtures/globals.yml
- test/models/global_listing_test.rb
- test/models/global_test.rb
closes #67 
Task Outcome:
Completed as expected.
How to Evaluate:
Log in to alice@email.com and password. Then make some global requests from "global request forum" tab in nav. Then you can click "my requests" tab from nav, select my global requests and you should see only your user's global requests.
Search bar should function from every page (via nav bar search).
Close out/review button should be clear and understandable.
> MH-33 Global Request Personal View Index Revisited

- app/assets/stylesheets/application.scss
- app/controllers/static_pages_controller.rb
- app/models/review.rb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/globals/edit.html.erb
- app/views/globals/new.html.erb
- app/views/layouts/application.html.erb
- app/views/requests/edit.html.erb
- app/views/requests/new.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/home.html.erb
- app/views/videos/_form.html.erb
- app/views/videos/index.html.erb
- app/views/videos/show.html.erb
- config/routes.rb
- db/schema.rb
- test/fixtures/reviews.yml
- test/models/review_test.rb
closes #62 
Take completed
Added about page.
> MH-29 Updated Search Bar

- app/controllers/globals_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/videos_controller.rb
- app/models/review.rb
- app/models/video.rb
- app/views/reviews/_form.html.erb
- app/views/reviews/show.html.erb
- app/views/videos/_form.html.erb
- app/views/videos/show.html.erb
- db/migrate/20201115013149_addvkeytovideo.rb
- db/migrate/20201115024035_deletevkeyfromvideo.rb
- db/migrate/20201115024236_addvkeytoreviews.rb
- db/schema.rb
- test/fixtures/reviews.yml
- test/models/review_test.rb
closes #69 
Task Outcome:
Completed as expected.
How to Evaluate:
You are able to review videos now. Sign into alice@email.com or bobby@email.com password and post a video. If you are a third party user who is visiting Alice or Bob's page and click the video you can then review the video. It will be posted once you submit. All posted reviews listed below the video that has been reviewed. You are able to delete your review. The poster of the video is not able to delete reviews. All reviews, both video review and reviews submitted upon completion of direct request/global request are aggregated and posted together in "My Reviews" page.
> MH-34 Video Reviews

- app/controllers/my_notifications_controller.rb
Closes #72 
Task Outcome:
Task completed as expected
> HOTFIX: Notification Redirect

- app/views/layouts/application.html.erb
Closes #74
Task Outcome:
Task completed as expected
> SUPPORT: Commenting application.html.erb

- app/controllers/messages_controller.rb
- app/controllers/reviews_controller.rb
- app/models/message.rb
- app/views/messages/edit.html.erb
- app/views/messages/index.html.erb
- app/views/messages/new.html.erb
- app/views/messages/show.html.erb
- app/views/reviews/edit.html.erb
- app/views/reviews/index.html.erb
Closes #78 
Task Outcome:
Task completed as expected
> SUPPORT: Commenting to messages and reviews

- Gemfile
- app/controllers/application_controller.rb
- app/controllers/global_listings_controller.rb
- app/controllers/globals_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/requests_controller.rb
- app/controllers/reviews_controller.rb
- app/models/global.rb
- app/models/global_listing.rb
- app/models/request.rb
- app/models/review.rb
- app/models/user.rb
- app/views/global_listings/index.html.erb
- app/views/globals/edit.html.erb
- app/views/globals/index.html.erb
- app/views/globals/new.html.erb
- app/views/globals/show.html.erb
- app/views/requests/edit.html.erb
- app/views/requests/index.html.erb
- app/views/requests/new.html.erb
- app/views/requests/show.html.erb
- app/views/reviews/_form.html.erb
- app/views/reviews/index.html.erb
- app/views/reviews/show.html.erb
- app/views/users/show.html.erb
- app/views/videos/_form.html.erb
- app/views/videos/show.html.erb
- config/routes.rb
Closes #76 
Adds Comments and fixes minor bug. Adds login authentication to global request forum.
> Support: Comments to Request Models, Misc.

- app/views/users/index.html.erb
Closes #80 
Task Outcome:
Task completed as expected
> HOTFIX: Fixed search result
